hibernate:
    hbm2ddl:
        auto: update
    dialect:  org.hibernate.dialect.H2Dialect
spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:devDb
        username: sa
        password: ""